extends SceneTree

func _initialize() -> void:
	OS.set_environment("THREE_KINGDOM_MOBILE_UI_TEST", "1")
	var game = load("res://ThreeKingdom/ThreeKingdom.tscn").instantiate()
	root.add_child(game)
	await process_frame
	assert(game._is_mobile_ui())
	assert(game.menu_overlay.get_child(0).get_child(0).custom_minimum_size.x >= 700.0)
	game._show_encyclopedia()
	assert(game.encyclopedia_grid.columns == 2)
	assert(game.encyclopedia_content_scroll.get_meta("touch_scroll_enabled", false))
	assert(game.rune_inventory_scroll.get_meta("touch_scroll_enabled", false))
	game._set_encyclopedia_mode("bonds")
	assert(game.encyclopedia_bond_graph.get_meta("touch_pan_enabled", false))
	game.encyclopedia_overlay.hide()
	game._start_new_from_menu()
	assert(not game.enemy_title_label.visible)
	assert(not game.player_title_label.visible)
	assert(not game.enemy_roster_label.visible)
	assert(not game.roster_label.visible)
	assert(not game.phase_caption_label.visible)
	for pick in 3:
		game._choose_hero(game.choices[0])
	assert(game.phase == "placement")
	game._auto_place_player()
	assert(game._can_start_battle())
	game._start_battle()
	assert(game.battle_pause_button.visible)
	game._toggle_battle_pause()
	assert(game.battle_paused)
	assert(game.tick_timer.is_stopped())
	game._toggle_battle_pause()
	assert(not game.battle_paused)
	assert(not game.tick_timer.is_stopped())
	game.tick_timer.stop()
	OS.unset_environment("THREE_KINGDOM_MOBILE_UI_TEST")
	quit()
